### ISSUE TITLE
Request: Add support for the Square Enix Twitch extension

### ISSUE THREAD

**Issue by Seb3thehacker** [CommanderRoot/disable-twitch-extensions#1]
Please add support for blacklisting/whitelisting the Square Enix Twitch extension.

Been loving it so far, thank you!

**Comment by CommanderRoot** [comment]
You mean this one https://dashboard.twitch.tv/extensions/ppi0gsh1fr6f1negsjas7t7s5cqzgk ?
If so it's already on the list. If it's not that one please post the link to it so I can easily find it.

**Comment by Seb3thehacker** [comment]
My bad. Its on there. I looked 3 times and only found it now on the 4th one 😑. Thanks!
